media:
  storage:
    path: '/Users/ppolubentcev/Projects/media'
  search:
    radius: 50

geo:
  geo-tree:
    root:
      id: 1

spring:
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    driverClassName: org.h2.Driver