geo:
  geo-tree:
    root:
      id: 1

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    driverClassName: org.h2.Driver