secrets:
  aws:
    credentials:
      file-path: /Users/ppolubentcev/Downloads/cred.config

media:
  storage:
    s3-bucket: perspective-media-thumbnail
  search:
    radius: 5000

geo:
  geo-tree:
    root:
      id: 1

spring:
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url:
    username:
    password:
